# Monitoring
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: telegraf-{{ .Release.Name }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: labby-monitoring
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/monitoring-config.yaml") . | sha256sum }}
        checksum/secrets: {{ include (print $.Template.BasePath "/monitoring-secret.yaml") . | sha256sum }}
    spec:
      containers:
        - resources:
            requests:
              cpu: 0.15
          securityContext:
            privileged: true
          image: telegraf:1.2.1-alpine
          name: telegraf
          env:
            - name: INFLUX_DB_INGEST_USER
              valueFrom:
                secretKeyRef:
                  name: influx-db-ingest
                  key: username
            - name: INFLUX_DB_INGEST_PASS
              valueFrom:
                secretKeyRef:
                  name: influx-db-ingest
                  key: password
          volumeMounts:
            - name: telegraf-config
              mountPath: /etc/telegraf
              readOnly: true
      volumes:
        - name: telegraf-config
          configMap:
            name: telegraf-config
